# Generated by go2rpm 1.18.0
%bcond check 1

# https://github.com/openpubkey/opkssh
%global goipath         github.com/openpubkey/opkssh
Version:                0.10.0

%gometa -L -f


Name:           golang-github-openpubkey-opkssh
Release:        %autorelease
Summary:        Opkssh (OpenPubkey SSH)

# Generated by go-vendor-tools
License:        Apache-2.0 AND BSD-2-Clause AND BSD-3-Clause AND ISC AND MIT AND Unlicense
URL:            %{gourl}
Source0:        %{gosource}
# Generated by go-vendor-tools
Source1:        %{archivename}-vendor.tar.bz2
Source2:        go-vendor-tools.toml

BuildRequires:  go-vendor-tools

%description
Opkssh (OpenPubkey SSH).

%prep
%goprep -A
%setup -q -T -D -a1 %{forgesetupargs}
%autopatch -p1

%generate_buildrequires
%go_vendor_license_buildrequires -c %{S:2}

%build
%global gomodulesmode GO111MODULE=on
%gobuild -o %{gobuilddir}/bin/opkssh %{goipath}

%install
%go_vendor_license_install -c %{S:2}
install -m 0755 -vd                     %{buildroot}%{_bindir}
install -m 0755 -vp %{gobuilddir}/bin/* %{buildroot}%{_bindir}/

%check
%go_vendor_license_check -c %{S:2}
%if %{with check}
%gotest ./...
%endif

%files -f %{go_vendor_license_filelist}
%license vendor/modules.txt
%doc docs CODE-OF-CONDUCT.md CONTRIBUTING.md README.md SECURITY.md
%doc scripts/install-linux-script.md scripts/installing.md
%{_bindir}/opkssh


%changelog
%autochangelog
